### ISSUE TITLE
Characteristic discovery not being shutdown after a call to BLE::shutdown()

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/ble-nrf51822#110]
It seems that the nRF5xCharacteristicDescriptorDiscoverer is not being shutdown at all after a call to BLE::shutdown(), see https://github.com/ARMmbed/ble-nrf51822/blob/master/source/nRF5xGattClient.h#L177. This might result in callbacks not being cleared and some resources not being released.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1884

**Comment by pan-** [comment]
Fixed.Looks like it is fixed: https://github.com/ARMmbed/ble-nrf51822/blob/master/source/nRF5xGattClient.h#L184
@andresag01 Could you update the ticket ?
