### ISSUE TITLE
No path specified when including sdk headers

### ISSUE THREAD

**Issue by aracosta1** [ARMmbed/ble-nrf51822#114]
when including "ble.h" from the sdk no path is specified and this can create problem when building the code with Emblitz on windows or on system with case insensitive filesystem. The compiler use the first ble.h it find in the search path order and it use the one from the BLE_API. It's better to use some kind of path like "s130/headers/ble.h" to disambiguate the file.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2095

**Comment by pan-** [comment]
The SDK is not here anymore and this issue has been fixed in the SDK: 
https://github.com/ARMmbed/nrf51-sdk/pull/26

I close this.
