### ISSUE TITLE
Crash when nRF5xGattClient::discoverCharacteristicDescriptors is called with a characteristic without descriptors

### ISSUE THREAD

**Issue by pan-** [ARMmbed/ble-nrf51822#116]
Calling the function `nRF5xGattClient::discoverCharacteristicDescriptors` on a characteristic without descriptors just crash the board.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2276

**Comment by pan-** [comment]
Not an issue of ble-nrf51822, it is an issue of ble-cliapp. 
I has been captured here: https://github.com/ARMmbed/ble-cliapp/issues/55.
