### ISSUE TITLE
GattServer::write return an error even when there is no error

### ISSUE THREAD

**Issue by pan-** [ARMmbed/ble-nrf51822#119]
The function `nRF5xGattServer::write` return an error even if the write operation succeed.

The result value is not updated as seen here: https://github.com/ARMmbed/ble-nrf51822/blob/master/source/nRF5xGattServer.cpp#L272-L278. The function will always return `BLE_ERROR_INVALID_STATE`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2286

**Comment by pan-** [comment]
Fixed by PR #120 .
