### ISSUE TITLE
service discovery should be able to match against long UUIDs

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/ble-nrf51822#18]
Currently we've tested it only for short UUIDs.
When a long UUID is discovered, it needs to be added to the Nordic stack.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-853

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1029

**Comment by jrobeson** [comment]
added to the nordic stack where?

**Comment by rgrover** [comment]
The nordic stack likes to deal with UUIDs using a short internal representation. https://github.com/ARMmbed/ble-nrf51822/blob/master/source/btle/custom/custom_helper.cpp#L82
When a long UUID is discovered during service discovery, it is represented as an invalid type (or a user-defined type; I forget which). The long UUID needs to be fetched explicitly and added to the ble stack before it can be represented again using the short form. https://github.com/ARMmbed/ble-nrf51822/blob/master/source/btle/custom/custom_helper.cpp#L82

**Comment by pan-** [comment]
This is fixed with latest versions of nrf51822.
It even discover 128 bits UUID descriptors.
