### ISSUE TITLE
handle all possible types of ble_uuid_t during service discovery

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/ble-nrf51822#19]

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-852

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1028

**Comment by pan-** [comment]
This is fixed with latest versions of nrf51822.
It even discover 128 bits UUID descriptors.
