### ISSUE TITLE
remove duplication of global static variable BLE_EVT_BUFFER

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/ble-nrf51822#39]
With https://github.com/ARMmbed/ble-nrf51822/pull/32, we duplicated the call to SOFTDEVICE_HANDLER_INIT(), which now results in two separate instances of BLE_EVT_BUFFER objects. This can be avoided.

**Comment by rgrover** [comment]
notify @jpbrucker

**Comment by rgrover** [comment]
@jpbrucker: could you please review this change?

**Comment by jpbrucker** [comment]
Looks good to me. Sorry about that!
