### ISSUE TITLE
Error real cause loss in nRF5xGattServer.cpp

### ISSUE THREAD

**Issue by fabiencomte** [ARMmbed/ble-nrf51822#44]
Hello,
For me theses lines look incorrect. We have a busy result for all errors but on top application busy could fire a wait and retry action, another errors could fire a cancel action. My proposition is to give multiple error results for this function.

250         if (error != ERROR_NONE) { 
251             returnValue = BLE_STACK_BUSY; 
252         }

**Comment by rgrover** [comment]
I agree with you. Error returns from Nordic SDK should trigger more fine-grained responses in this case. Would you be able to submit a pull request for the changes you care about?

**Comment by fabiencomte** [comment]
Pull request proposed
