### ISSUE TITLE
rename the bootloader files with _fota in the name?

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/ble-nrf51822#51]
It wouldn't be clear that they are fota by browsing the source.

**Comment by rgrover** [comment]
I don't understand the question. Could you please point out which files you're referring to?

**Comment by jrobeson** [comment]
I was referring to this commit: https://github.com/ARMmbed/ble-nrf51822/commit/8f853d96769995675e9036529088661a34f55e9b

Will non FOTA bootloaders ever be stored?

**Comment by rgrover** [comment]
Presently, a bootloader is only necessary for FOTA. If/when this changes, adding a _FOTA extension to the name might be useful. I believe this is not necessary for the moment,

**Comment by jrobeson** [comment]
ah, I wasn't clear .. probably due to nomenclature of another project.
