### ISSUE TITLE
nRF5xn::init don't verify if errors have occurred during btle_init

### ISSUE THREAD

**Issue by pan-** [ARMmbed/ble-nrf51822#59]
See this at: https://github.com/ARMmbed/ble-nrf51822/blob/master/source/nRF5xn.cpp#L94 .
The init process should check and report if something has gone wrong

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1168

**Comment by andresag01** [comment]
@pan- @rgrover : It is easy to simply return `BLE_ERROR_UNSPECIFIED` when a call to `ble_init()` fails. However, this might not be the ideal solution. The main problem is that we do not have sufficient error codes to be more specific about the cause of the problem. Is it acceptable to return `BLE_ERROR_UNSPECIFIED` when there is a failed call to `ble_init()`? Should we are more error codes to [the BLE API](https://github.com/ARMmbed/ble/blob/develop/ble/blecommon.h#L53)?

**Comment by pan-** [comment]
What would you want to return ?

**Comment by andresag01** [comment]
Submitted a pull request https://github.com/ARMmbed/ble/pull/155 to add another error code to the API
